name: CI/CD for Spring Boot with Maven

on:
  push:
    branches:
      - main

jobs:


  deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:
    - name: Setup key
      id: setup-key
      env:
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
      run: |
          echo "$DEPLOY_KEY" >> $HOME/key.pem
          chmod 400 $HOME/key.pem
    - name: Connect SSH and Restart Services
      run: |
        ssh -o StrictHostKeyChecking=no -i $HOME/key.pem ubuntu@ec2-51-20-55-82.eu-north-1.compute.amazonaws.com 'git clone https://github.com/CameLoopers/blinder-api.git && cd /home/ubuntu/blinder-api/ && mvn clean package && sudo systemctl restart blinderapi && sudo systemctl restart nginx' &
        sleep 5  # Allow some time for the SSH command to initiate before moving to the next step
         
