name: CI/CD for Spring Boot with Maven

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '17'

    - name: Build with Maven
      run: mvn clean install

  deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:
    - name: Deploy to server
      uses: appleboy/scp-action@v0.2.0
      with:
        host: ${{ secrets.DEPLOY_HOST }}
        username: ${{ secrets.DEPLOY_USER }}
        key: ${{ secrets.DEPLOY_KEY }}
        port: ${{ secrets.DEPLOY_PORT }}
        source: '/home/ubuntu/blinder-api/target/api-0.0.1-SNAPSHOT.jar'  # Maven output directory
        target: '/path/to/deployment/directory/'
