name: CI/CD for Spring Boot with Maven

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '17'

    - name: Build with Maven
      run: mvn clean package
      
    - name: Copy JAR to EC2
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.DEPLOY_KEY }}
        source: "target/api-0.0.1-SNAPSHOT.jar"
        target: "/home/ubuntu/blinder-api/target/api-0.0.1-SNAPSHOT.jar"

  deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:
    - name: Setup key
      id: setup-key
      env:
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
      run: |
          echo "$DEPLOY_KEY" >> $HOME/key.pem
          chmod 400 $HOME/key.pem
    - name: Connect SSH and Restart Services
      run: |
        ssh -o StrictHostKeyChecking=no -i $HOME/key.pem ubuntu@ec2-51-20-55-82.eu-north-1.compute.amazonaws.com 'sudo systemctl restart blinderapi && sudo systemctl restart nginx' &
        sleep 5  # Allow some time for the SSH command to initiate before moving to the next step
         
